### ISSUE TITLE
Exception running default helloworld code snippet

### ISSUE THREAD

**Issue by freakynit** [ensdomains/ensjs-v2#24]
Getting this exception stacktrace trying default hello world snippet:
```
Unhandled rejection TypeError: this.provider.sendAsync is not a function
    at RequestManager.sendAsync (/Users/nitin/ens/node_modules/ethereum-ens/node_modules/web3/lib/web3/requestmanager.js:80:19)
    at get (/Users/nitin/ens/node_modules/ethereum-ens/node_modules/web3/lib/web3/property.js:116:33)
    at new ENS (/Users/nitin/ens/node_modules/ethereum-ens/index.js:420:77)
    at Object.<anonymous> (/Users/nitin/ens/app.js:5:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
node: v9.2.1
npm: 5.5.1
ethereum-ens: 0.7.4
OS: MacOS High Sierra (10.13.2 (17C88)) (MacBook Pro (Retina, 13-inch, Mid 2014))

**Comment by Arachnid** [comment]
What version of web3 are you using?

**Comment by freakynit** [comment]
@Arachnid : web3@1.0.0-beta.35

**Comment by Arachnid** [comment]
@tetratorus, can you take a look? Seems like it might be an issue with 1.0 support.

**Comment by kvhnuke** [comment]
@Arachnid I ran into the same issue when I installed via `npm install ethereum-ens` I think the index on npm is different from github version `npm install https://github.com/ensdomains/ensjs.git` fixed the issue
